# Generated by Django 3.2.4 on 2021-07-02 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='q_date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
