# Generated by Django 3.2.4 on 2021-07-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20210708_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='contact_name',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='contact_phone',
            field=models.CharField(blank=True, default='867-5309', max_length=15),
        ),
    ]
