# Generated by Django 3.2.4 on 2021-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='contact_phone',
            field=models.CharField(default='867-5309', max_length=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_accepted',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='lead_time',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='part_cost',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='part_description',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='part_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='part_qty',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='q_addepted',
            field=models.BooleanField(default=False),
        ),
    ]
