# Generated by Django 3.2.4 on 2021-07-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20210708_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='part_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
