# Generated by Django 3.2.4 on 2021-07-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20210708_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
