# Generated by Django 3.2.4 on 2021-07-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_quote_quote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_total',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
