# Generated by Django 3.2.4 on 2021-07-13 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quote_quote_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=10)),
                ('o_title', models.CharField(max_length=200)),
                ('o_start_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
