# Generated by Django 3.2.4 on 2021-07-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_openorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='q_addepted',
            new_name='q_accepted',
        ),
    ]
